apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: parasol-store-app
  description: "Store application component for the Parasol project in the Red Hat PE Workshop"
  owner: redhat-pe-workshop
  annotations:
    github.com/project-slug: redhat-pe-workshop/parasol-store-app
    backstage.io/techdocs-ref: url:https://github.com/redhat-pe-workshop/parasol-store-app
  tags:
    - application
    - store
    - parasol
    - redhat
spec:
  type: service
  lifecycle: experimental
  owner: redhat-pe-workshop
  system: parasol
  repository: https://github.com/redhat-pe-workshop/parasol-store-app
  dependsOn:
    - component:default/parasol-db
  providesApis:
    - default/parasol-store-app-api
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: parasol-store-app-api
  description: "OpenAPI specification for the Parasol Store Application"
  owner: redhat-pe-workshop
  tags:
    - api
    - openapi
    - parasol
spec:
  type: openapi
  lifecycle: experimental
  owner: redhat-pe-workshop
  definition: 
    $text: https://github.com/OAI/OpenAPI-Specification/blob/main/examples/v3.0/api-with-examples.json
